### ISSUE TITLE
Incorrect r check in dECDSA.cpp

### ISSUE THREAD

**Issue by GregoryMorse** [whibox/whibox-contest-2021_supplementary-materials#1]
We see in the source code on lines 222-224 (https://github.com/whibox/whibox-contest-2021_supplementary-materials/blob/main/dECDSA.c):

```
    /* calculate r = Q[x] mod n, if r = 0, restart. */
    mpz_mod(r, Q->x, n);
    if (mpz_cmp_ui(Q->x, 0) == 0) {
```

Suggest:
`if (mpz_cmp_ui(r, 0) == 0) {`
which agrees with the comment and algorithm description here: https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm

Despite the astronomically low chance of this occurring.  Specifically if `Q->x==n` expressed in gmp then `r==0` but the condition is not met.  Rather than a modulo, comparison and subtraction given the bit size might be more appropriate e.g. `r = Q->x >= n ? Q->x - n : Q->x;` again assuming it is expressed in gmp.

**Comment by junwei-wang** [comment]
`r` check is fixed in https://github.com/whibox/whibox-contest-2021_supplementary-materials/pull/2.
