### ISSUE TITLE
Memory leaks in dECDSA.c

### ISSUE THREAD

**Issue by GregoryMorse** [whibox/whibox-contest-2021_supplementary-materials#3]
There is a memory leak of G in the main signature routine which should have a `point_clear(G);` before returning after the loop.
Also in point addition when an inverse occurs, point_init_infinity(R) always leaks memory and should call point_clear(R) before reinitializing mpz_t big integers.

**Comment by rben-dev** [comment]
Hi @GregoryMorse 

Thanks for this report: this should be fixed in the 2024 supplementary material repo (https://github.com/whibox/whibox-contest-supplementary-materials).

Regards,
